# 로컬 테스트용
version: '3'
services:
  node:
    build:
      context: .
    ports:
      - 8001:8000
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
