version: '3'
services:
  node:
    image: ${IMAGE}:${TAG}
    ports:
      - 8001:8000
    depends_on:
      - mysql
    networks:
      - server
  mysql:
    image: mysql:5.7
    volumes:
      - /var/potato_db:/var/lib/mysql
    networks:
      - server
  web:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
networks:
  server:
    driver: bridge
